<?xml version="1.0"?>
<package format="2">
  <name>occupancy_map_generator</name>
  <version>0.0.0</version>
  <description>Occupancy map generator module</description>
  <maintainer email="your_email@example.com">Your Name</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>

  <export>
    <python>
      <module>occupancy_map_generator</module>
    </python>
  </export>
</package>